# 3. Matrix Multiplications

A basic understanding of python and numpy arrays is useful for understanding the code snippets.

1. [Basics](#1.-Basics)
1. [Partitioned](#2.-Partitioned)
1. [Special Properties](#3.-Special-Properties)

In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


## 1. Basics

As mentioned in the previous notebook, the standard way of multiplying two matrices is depicted as the multiplication of each row of $A$ by each column of $B$. 

![](https://notebooks.azure.com/menziess/libraries/Python-Linear-Algebra/raw/res%2FMatrix_multiplication_diagram_2.svg.png)

Columns of the resulting matrix $C$ are combinations of columns of $A$. Rows of $C$ are combinations of rows of $B$.

Including the standard dot product way, there are other ways to interpret matrix multiplications:

1. Inner Product (Standard)
1. Matrix - Column Vector
1. Row Vectors - Matrix
1. Outer Product

In the examples we will use the matrices 
$
A = \begin{bmatrix}
  -2 & 1 & 0 \\
  3 & 0 & 1 \\
  1 & 2 & 1 \\
\end{bmatrix}
$
and
$
B = \begin{bmatrix}
  1 & -1 & 2 \\
  -1 & 1 & 0 \\
  2 & 1 & 2 \\
\end{bmatrix}
$

In [2]:
# Our matrices A and B
A = np.matrix("-2 1 0; 3 0 1; 1 2 1")
B = np.matrix("1 -1 2; -1 1 0; 2 1 2")

# Rows and columns of A
a0t, a1t, a2t = [row[0] for row in A]
a0,  a1,  a2  = [A[:, i] for i in range(len(A))]

# Rows and columns of B
b0t, b1t, b2t = [row[0] for row in B]
b0,  b1,  b2  = [B[:, i] for i in range(len(B))]

print(A @ B, "Result for comparison")

[[-3  3 -4]
 [ 5 -2  8]
 [ 1  2  4]] Result for comparison


$
AB = \begin{bmatrix}
  -3 & 3 & -4 \\
  5 & -2 & 8 \\
  1 & 2 & 4 \\
\end{bmatrix}
$

### 1.1 Inner Product (Standard)

Each row of $A$ times each column of $B$
$$C_{ij} = a_i^T b_j$$

In [3]:
print(a0t @ b0, "Top left component of C")

[[-3]] Top left component of C


### 1.2 Matrix - Column Vector

Matrix $A$ times each column of $B$

$$c_j = A b_j$$

In [4]:
print(A @ b0, "First column of C")

[[-3]
 [ 5]
 [ 1]] First column of C


### 1.3 Row Vectors - Matrix

Each row of $A$ times the matrix $B$

$$c_i^T = a_i^T B$$

In [5]:
print(a0t @ B, "First row of C")

[[-3  3 -4]] First row of C


### 1.4 Outer Product

The sum of each column of $A$ times each row of $B$

$$C = \sum_{j = 0}^{n_A} a_j b_i^T$$

In [6]:
C = a0 @ b0t
print(C, "Outer product of first column of A times first row of B")
C = a1 @ b1t + C
print(C, "plus second column of A times second row of B")
C = a2 * b2t + C
print(C, "plus third column of A times third row of B")

[[-2  2 -4]
 [ 3 -3  6]
 [ 1 -1  2]] Outer product of first column of A times first row of B
[[-3  3 -4]
 [ 3 -3  6]
 [-1  1  2]] plus second column of A times second row of B
[[-3  3 -4]
 [ 5 -2  8]
 [ 1  2  4]] plus third column of A times third row of B


## 2. Partitioned

The multiplication of partitions of $A$ and $B$ results in the partitions of $C$

$$
\left[
\begin{array}{c|c}
A_1 & A_2 \\
\hline
A_3 & A_4
\end{array}
\right]
\left[
\begin{array}{c|c}
B_1 & B_2 \\
\hline
B_3 & B_4
\end{array}
\right]
=
\left[
\begin{array}{c|c}
C_1 & C_2 \\
\hline
C_3 & C_4
\end{array}
\right]
$$

Each block / partition gets treated like simple matrix scalars / components. Therefore, the four multiplication interpretations can be used on these partitions.

In [7]:
A = np.linspace(0, 24, 25).reshape([5, 5])
B = np.linspace(25, 49, 25).reshape([5, 5])
print(A @ B, "Result for comparison")

[[ 400.  410.  420.  430.  440.]
 [1275. 1310. 1345. 1380. 1415.]
 [2150. 2210. 2270. 2330. 2390.]
 [3025. 3110. 3195. 3280. 3365.]
 [3900. 4010. 4120. 4230. 4340.]] Result for comparison


In [8]:
# Partitioning matrices A and B into 2x2, 2x3, 3x2, and 3x2 blocks
A1, A2, A3, A4 = A[0:2, 0:2], A[0:2, 2:], A[2:, 0:2], A[2:, 2:], 
B1, B2, B3, B4 = B[0:2, 0:2], B[0:2, 2:], B[2:, 0:2], B[2:, 2:],

# Using standard matrix multiplication (dot / inner product)
C1 = A1 @ B1 + A2 @ B3
C2 = A1 @ B2 + A2 @ B4
C3 = A3 @ B1 + A4 @ B3
C4 = A3 @ B2 + A4 @ B4

# Putting C1 on top of C3, C2 on top of C4, besides eachother to form C
C = np.concatenate((np.concatenate((C1, C3)), np.concatenate((C2, C4))), axis=1)
print(C, "It worked")

[[ 400.  410.  420.  430.  440.]
 [1275. 1310. 1345. 1380. 1415.]
 [2150. 2210. 2270. 2330. 2390.]
 [3025. 3110. 3195. 3280. 3365.]
 [3900. 4010. 4120. 4230. 4340.]] It worked


## 3. Special Properties

In addition to the properties listed in notebook [2. Matrices](./2.%20Matrices.ipynb), there are some special properties related to matrix multiplications:

1. Transpose
1. Inverse

In [28]:
A = np.matrix([
    [1, 3],
    [2, 7]])
B = np.matrix([
    [4, 7],
    [2, 6]])

### 3.1 Transpose

Transposing a matrix causes a matrix to flip along its diagonal:

In [22]:
print(A.T)
print((A.T).T)

[[1 2]
 [3 7]]
[[1 3]
 [2 7]]


If the matrix product is defined, then:
$$A^T + B^T = (A + B)^T$$
$$(AB)^T = B^T A^T$$

In [29]:
transpose_addition = lambda A, B: (A.T + B.T == (A + B).T).all()
transpose_multiplication = lambda A, B: ((A @ B).T == B.T @ A.T).all()

transpose_addition(A, B) and transpose_multiplication(A, B)

True

### 3.2 Inverse

The inverse matrix exists only for square nonsingular matrices (whose determinant is nonzero).

The inverse of a matrix $A$ is defined as matrix $A^{-1}$ such that the product of the matrix and its own inverse results in the identity matrix:

In [24]:
A @ A.I

matrix([[1., 0.],
        [0., 1.]])

The inverse of a product of matrices equals the inverse of the second matrix times the inverse of the first matrix:

In [46]:
print((A @ B).I)
print(B.I @ A.I)

# We prevent rounding errors before checking equality
I1 = np.round(B.I @ A.I, 2)
I2 = np.round((A @ B).I, 2)
(I1 == I2).all()

[[ 5.6 -2.5]
 [-2.2  1. ]]
[[ 5.6 -2.5]
 [-2.2  1. ]]


True